one_to_ten_list = list(range(1, 10))
one_to_two_list = list(range(11, 20))
two_to_three_list = list(range(21, 30))
three_to_four_list = list(range(31, 40))
four_to_five_list = list(range(41, 50))
five_to_six_list = list(range(51, 60))
six_to_seven_list = list(range(61, 70))
seven_to_eight_list = list(range(71, 80))
eight_to_nine_list = list(range(81, 90))
nine_to_ten_list = list(range(91, 100))

print(one_to_ten_list)
print(one_to_two_list)
print(two_to_three_list)
print(three_to_four_list)
print(four_to_five_list)
print(five_to_six_list)
print(six_to_seven_list)
print(seven_to_eight_list)
print(eight_to_nine_list)
print(nine_to_ten_list)